<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- tells Maven which POM model format is being used -->
    <modelVersion>4.0.0</modelVersion>

    <!-- project identification -->
    <groupId>dev.notduey</groupId> <!-- groupId identifies broader organization/namespace -->
    <artifactId>closet-query</artifactId> <!-- artifactId identifies the specific project -->
    <version>1.0</version>
    <name>ClosetQuery</name>

    <!-- project-wide settings -->
    <properties>
        <maven.compiler.release>26</maven.compiler.release> <!-- version of Java to compile -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding> <!-- text encoding -->
    </properties>

    <!-- external requirements -->
    <dependencies>
        <!-- Source: https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.53.2.1</version>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime -->
        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.29.0</version>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/ai.djl.huggingface/tokenizers -->
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
            <version>0.36.0</version>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>3.2.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Source: https://mvnrepository.com/artifact/org.codehaus.mojo/exec-maven-plugin -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <configuration>
                    <mainClass>dev.notduey.closetquery.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>