package dev.notduey.closetquery.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import dev.notduey.closetquery.model.Piece;

/**
 * Handles all SQLite operations involving wardrobe pieces.
 *
 * <p>This class acts as the main data-access layer for ClosetQuery. It handles
 * adding and removing pieces, retrieving pieces for structured questions,
 * running simple statistics, and converting database rows back into
 * {@link Piece} objects.</p>
 *
 * <p>Keeping the SQL here also lets the rest of the app work with Piece
 * objects without needing to know how the database is queried.</p>
 */
public class PieceRepository {

    /**
     * Adds a new wardrobe piece using the database defaults for its ID,
     * date added, last worn date, and wear count.
     *
     * @param piece piece to add
     * @return the ID generated by SQLite for the new piece
     * @throws SQLException if the piece cannot be inserted
     */
    public int addPiece(Piece piece) throws SQLException {
        String sql = """
                INSERT INTO pieces (
                    brand,
                    name,
                    category,
                    size,
                    color,
                    colorway,
                    season,
                    occasion,
                    fit,
                    materials,
                    notes
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """; // placeholders (?) keep values separate from SQL structure

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            // SQL handles id and date_added, last_worn, times_worn with default values
            statement.setString(1, piece.getBrand()); // first ? = piece brand
            statement.setString(2, piece.getName()); // second ? = piece name
            statement.setString(3, piece.getCategory());
            statement.setString(4, piece.getSize());
            statement.setString(5, piece.getColor());
            statement.setString(6, piece.getColorway());
            statement.setString(7, piece.getSeason());
            statement.setString(8, piece.getOccasion());
            statement.setString(9, piece.getFit());
            statement.setString(10, piece.getMaterials());
            statement.setString(11, piece.getNotes());

            try (ResultSet resultSet = statement.executeQuery()) { // executeQuery to return id
                if (resultSet.next()) {
                    return resultSet.getInt("id");
                }
            }
        }

        throw new SQLException("Piece inserted but no id returned");
    }

    /**
     * Adds a wardrobe piece that already has existing wear history.
     *
     * <p>Unlike {@link #addPiece(Piece)}, this includes the piece's last worn date
     * and wear count while still letting SQLite generate the ID and date added.</p>
     *
     * @param piece existing wardrobe piece to add
     * @return the ID generated by SQLite for the new piece
     * @throws SQLException if the piece cannot be inserted
     */
    public int addExistingPiece(Piece piece) throws SQLException {
        String sql = """
                INSERT INTO pieces (
                    brand,
                    name,
                    category,
                    size,
                    color,
                    colorway,
                    season,
                    occasion,
                    fit,
                    materials,
                    notes,
                    last_worn,
                    times_worn
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """;

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setString(1, piece.getBrand());
            statement.setString(2, piece.getName());
            statement.setString(3, piece.getCategory());
            statement.setString(4, piece.getSize());
            statement.setString(5, piece.getColor());
            statement.setString(6, piece.getColorway());
            statement.setString(7, piece.getSeason());
            statement.setString(8, piece.getOccasion());
            statement.setString(9, piece.getFit());
            statement.setString(10, piece.getMaterials());
            statement.setString(11, piece.getNotes());
            statement.setString(12, piece.getLastWorn());
            statement.setInt(13, piece.getTimesWorn());

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getInt("id");
                }
            }
        }

        throw new SQLException("Piece inserted but no id returned");
    }

    /**
     * Removes a wardrobe piece by its database ID.
     *
     * @param id ID of the piece to remove
     * @return number of rows deleted, normally 1 if the piece existed or 0 if not
     * @throws SQLException if the delete operation fails
     */
    public int removePiece(int id) throws SQLException {
        String sql = "DELETE FROM pieces WHERE id = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setInt(1, id);

            return statement.executeUpdate();
        }
    }

    /**
     * Retrieves every wardrobe piece currently stored in SQLite.
     *
     * @return all wardrobe pieces
     * @throws SQLException if the pieces cannot be loaded
     */
    public List<Piece> getAllPieces() throws SQLException {
        String sql = """
            SELECT
                id,
                brand,
                name,
                category,
                size,
                color,
                colorway,
                season,
                occasion,
                fit,
                materials,
                notes,
                date_added,
                last_worn,
                times_worn
            FROM pieces
            """;

        List<Piece> pieces = new ArrayList<>(); // stores Piece objects returned from db

        try (Connection connection = DatabaseConnection.getConnection();

            // statement here is valid, but using prepared statement for data-access code is good practice
             PreparedStatement statement = connection.prepareStatement(sql); 
             ResultSet resultSet = statement.executeQuery() // run SQL query
        ) {
            // resultSet has a cursor that starts before the first row
            while (resultSet.next()) { // move cursor to next returned row
                pieces.add(mapPiece(resultSet));
            }
        }

        return pieces;
    }

    /**
     * Finds a single wardrobe piece by its ID.
     *
     * @param id database ID to search for
     * @return matching piece, or {@code null} if no piece exists with that ID
     * @throws SQLException if the query fails
     */
    public Piece getPieceById(int id) throws SQLException {
        String sql = "SELECT * FROM pieces WHERE id = ?";

        try (
            Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setInt(1, id);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next()) {
                    return null;
                }

                return mapPiece(resultSet);
            }
        }
    }

    /**
     * Retrieves the most-worn pieces, optionally limited to one category.
     *
     * @param limit maximum number of pieces to return
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces ordered from most worn to least worn
     * @throws SQLException if the query fails
     */
    public List<Piece> getMostWornPieces(int limit, String category) throws SQLException {
        validateLimit(limit);

        String sql;

        // Determine SQL query based on category
        if (category == null) {
            sql = """
                SELECT *
                FROM pieces
                ORDER BY times_worn DESC, id ASC
                LIMIT ?
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE category = ? 
                ORDER BY times_worn DESC, id ASC
                LIMIT ?
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category == null) { // only limit
                statement.setInt(1, limit);
            } else { // category and limit
                statement.setString(1, category);
                statement.setInt(2, limit);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves the least-worn pieces, optionally limited to one category.
     *
     * @param limit maximum number of pieces to return
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces ordered from least worn to most worn
     * @throws SQLException if the query fails
     */
    public List<Piece> getLeastWornPieces(int limit, String category) throws SQLException {
        validateLimit(limit);

        String sql;

        if (category == null) {
            sql = """
                SELECT *
                FROM pieces
                ORDER BY times_worn ASC, id ASC
                LIMIT ?
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE category = ? 
                ORDER BY times_worn ASC, id ASC
                LIMIT ?
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category == null) {
                statement.setInt(1, limit);
            } else {
                statement.setString(1, category);
                statement.setInt(2, limit);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves pieces that have never been worn.
     *
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces with a wear count of zero
     * @throws SQLException if the query fails
     */
    public List<Piece> getNeverWornPieces(String category) throws SQLException {
        String sql;

        if (category == null) {
            sql = """
                SELECT *
                FROM pieces
                WHERE times_worn = 0
                ORDER BY id ASC
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE times_worn = 0
                    AND category = ?
                ORDER BY id ASC
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (
            Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category != null) { // add category if exists
                statement.setString(1, category);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves the most recently worn pieces, optionally limited to one category.
     *
     * @param limit maximum number of pieces to return
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces ordered by most recent last-worn date
     * @throws SQLException if the query fails
     */
    public List<Piece> getMostRecentlyWornPieces(int limit, String category) throws SQLException {
        validateLimit(limit);

        String sql;

        if (category == null) {  // id ASC tiebreaker
            sql = """
                SELECT *
                FROM pieces
                ORDER BY 
                    last_worn DESC,
                    id ASC
                LIMIT ?
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE category = ?
                ORDER BY 
                    last_worn DESC,
                    id ASC
                LIMIT ?
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category == null) { // only limit
                statement.setInt(1, limit);
            } else { // category and limit
                statement.setString(1, category);
                statement.setInt(2, limit);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves the least recently worn pieces, optionally limited to one category.
     *
     * <p>Pieces without a last-worn date are returned first, followed by pieces
     * ordered from oldest to newest last-worn date.</p>
     *
     * @param limit maximum number of pieces to return
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces ordered by least recent wear history
     * @throws SQLException if the query fails
     */
    public List<Piece> getLeastRecentlyWornPieces(int limit, String category) throws SQLException {
        validateLimit(limit);

        String sql;

        if (category == null) {  // never worn pieces first then ordered by last worn
            sql = """
                SELECT *
                FROM pieces
                ORDER BY 
                    last_worn IS NOT NULL,
                    last_worn ASC,
                    id ASC
                LIMIT ?
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE category = ?
                ORDER BY 
                    last_worn IS NOT NULL,
                    last_worn ASC,
                    id ASC
                LIMIT ?
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category == null) { // only limit
                statement.setInt(1, limit);
            } else { // category and limit
                statement.setString(1, category);
                statement.setInt(2, limit);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves the pieces added to ClosetQuery most recently.
     *
     * @param limit maximum number of pieces to return
     * @param category category to filter by, or {@code null} for the full wardrobe
     * @return pieces ordered by date added
     * @throws SQLException if the query fails
     */
    public List<Piece> getRecentlyAddedPieces(int limit, String category) throws SQLException {
        validateLimit(limit);

        String sql;

        if (category == null) {  // id DESC as newer pieces have higher ids
            sql = """
                SELECT *
                FROM pieces
                ORDER BY date_added DESC, id DESC
                LIMIT ?
                """;
        } else {
            sql = """
                SELECT *
                FROM pieces
                WHERE category = ?
                ORDER BY date_added DESC, id DESC
                LIMIT ?
                """;
        }

        List<Piece> pieces = new ArrayList<>();

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            if (category == null) {
                statement.setInt(1, limit);
            } else {
                statement.setString(1, category);
                statement.setInt(2, limit);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Retrieves every piece belonging to a specific wardrobe category.
     *
     * @param category category to search for
     * @return all pieces in the category
     * @throws SQLException if the query fails
     */
    public List<Piece> getPiecesByCategory(String category) throws SQLException {
        String sql = """
            SELECT *
            FROM pieces
            WHERE category = ?
            ORDER BY id ASC
            """;

        List<Piece> pieces = new ArrayList<>();

        try (
            Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setString(1, category);

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    pieces.add(mapPiece(resultSet));
                }
            }
        }

        return pieces;
    }

    /**
     * Counts how many wardrobe pieces belong to a specific category.
     *
     * <p>The count is performed directly in SQLite instead of loading every
     * matching Piece into Java.</p>
     *
     * @param category category to count
     * @return number of pieces in the category
     * @throws SQLException if the query fails
     */
    public int countPiecesByCategory(String category) throws SQLException {
        String sql = """
                SELECT COUNT(*) AS total
                FROM pieces
                WHERE category = ?
                """;

        try (
            Connection connection = DatabaseConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setString(1, category);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getInt("total");
                }
            }
        }

        return 0;
    }

    /**
     * Converts the current ResultSet row into a Piece object.
     *
     * <p>This keeps the database-to-object mapping in one place instead of
     * repeating the same column reads throughout the repository.</p>
     *
     * @param resultSet result set currently positioned on a piece row
     * @return Piece reconstructed from the database row
     * @throws SQLException if a column cannot be read
     */
    private Piece mapPiece(ResultSet resultSet) throws SQLException {
        return Piece.fromDatabase(
            resultSet.getInt("id"),
            resultSet.getString("brand"),
            resultSet.getString("name"),
            resultSet.getString("category"),
            resultSet.getString("size"),
            resultSet.getString("color"),
            resultSet.getString("colorway"),
            resultSet.getString("season"),
            resultSet.getString("occasion"),
            resultSet.getString("fit"),
            resultSet.getString("materials"),
            resultSet.getString("notes"),
            resultSet.getString("date_added"),
            resultSet.getString("last_worn"),
            resultSet.getInt("times_worn")
        );
    }

    /**
     * Makes sure a structured query is given a valid positive result limit.
     *
     * @param limit result limit to validate
     * @throws IllegalArgumentException if the limit is zero or negative
     */
    private void validateLimit(int limit) {
        if (limit <= 0) {
            throw new IllegalArgumentException(
                    "Limit must be greater than 0."
            );
        }
    }

}